begin;

create table if not exists public.phase4_analysis_cache (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  analysis_type text not null check (analysis_type in ('life_profile', 'month', 'year')),
  period_key text not null check (length(period_key) between 6 and 32),
  chart_fingerprint text not null check (chart_fingerprint ~ '^[0-9a-f]{64}$'),
  calculation_profile text not null,
  classical_profile text not null,
  engine_version text not null,
  facts_version text not null,
  interpretation_version text not null,
  content_json jsonb not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint phase4_analysis_cache_identity unique (
    user_id,
    analysis_type,
    period_key,
    chart_fingerprint,
    calculation_profile,
    classical_profile,
    engine_version,
    facts_version,
    interpretation_version
  )
);

create index if not exists phase4_analysis_cache_expiry_idx
  on public.phase4_analysis_cache (expires_at);

create index if not exists phase4_analysis_cache_user_period_idx
  on public.phase4_analysis_cache (user_id, analysis_type, period_key);

alter table public.phase4_analysis_cache enable row level security;

revoke all on table public.phase4_analysis_cache from public, anon, authenticated;
grant select, insert, update, delete on table public.phase4_analysis_cache to service_role;
grant usage, select on sequence public.phase4_analysis_cache_id_seq to service_role;

commit;
